//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderWebsite.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Contact
    {
        [DisplayName("Mã liên hệ")]
        public int ContactID { get; set; }
        [DisplayName("Họ và tên")]
        public string ContactName { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Điện thoại")]
        public string Phone { get; set; }
        [DisplayName("Vấn đề")]
        public string Subject { get; set; }
        [DisplayName("Lời nhắn")]
        public string Message { get; set; }
    }
}
