//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderWebsite.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail
    {
        [DisplayName("Mã chi tiết đơn hàng")]
        public int OrderDetailID { get; set; }
        [DisplayName("Mã đơn hàng")]
        public int OrderID { get; set; }
        [DisplayName("Mã sản phẩm")]
        public int ProductID { get; set; }
        [DisplayName("Giá")]
        public Nullable<int> Price { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> Quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
