//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderWebsite.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        
        [DisplayName("Mã đơn hàng")]
        public int OrderID { get; set; }
        [DisplayName("Tên đơn hàng")]
        public string OrderName { get; set; }
        [DisplayName("Mã khách hàng")]
        public Nullable<int> UserID { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<int> Total { get; set; }
        [DisplayName("Ngày đặt hàng")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<int> Status { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
