//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderWebsite.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        
        [DisplayName("Mã sản phẩm")]
        public int ProductID { get; set; }
        [DisplayName("Mã loại")]
        public int CategoryID { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string ProductName { get; set; }
        [DisplayName("Mô tả")]
        public string Description { get; set; }
        [DisplayName("Giá")]
        public Nullable<int> Price { get; set; }
        [DisplayName("Số lượng")]
        public Nullable<int> Quantity { get; set; }
        [DisplayName("Hình ảnh")]
        public string ImageURL { get; set; }
        [DisplayName("Kích hoạt")]
        public Nullable<bool> IsActive { get; set; }
        [DisplayName("Phổ biến")]
        public Nullable<bool> IsPopular { get; set; }
        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
